# Generated by Django 5.1.7 on 2025-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_title', models.TextField(blank=True, null=True)),
                ('nyt_recipe_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('recipe_yield', models.TextField(blank=True, null=True)),
                ('total_time', models.TextField(blank=True, null=True)),
                ('steps', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('ingredients_full', models.TextField(blank=True, null=True)),
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recipe_data',
                'managed': False,
            },
        ),
    ]
